FROM haroldli/alist-base:latest

WORKDIR /home/choreouser

COPY files/* /home/choreouser/

ENV PM2_HOME=/tmp

LABEL MAINTAINER="Har01d"

ENV MEM_OPT="-Xmx512M"

COPY init.sh /home/choreouser/
COPY movie.sh /home/choreouser/
COPY entrypoint.sh /home/choreouser/

COPY target/application/ ./home/choreouser/

COPY data/version /home/choreouser/data/app_version

EXPOSE 4567 80

ENTRYPOINT ["/entrypoint.sh"]

CMD ["81", "--spring.profiles.active=production,xiaoya"]


